# 工作流名称（显示在GitHub Actions页面）
name: test github action

# 自定义运行显示名称（包含触发者用户名和表情）
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# 触发条件：当有代码push时触发
on: 
  #[push]  
  workflow_dispatch:

# 作业定义
jobs:
  # 作业ID（自定义名称）
  Explore-GitHub-Actions:
    # 运行环境：最新版Ubuntu
    runs-on: ubuntu-latest
    
    # 步骤序列
    steps:
      # 第一步：输出触发事件信息（使用emoji和变量）
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      # 第二步：输出运行环境信息
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      # 第三步：输出分支和仓库信息
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      # 第四步：检出代码（使用官方checkout action）
      - name: Check out repository code
        uses: actions/checkout@v4
      
      # 第五步：确认代码已克隆
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      # 第六步：准备就绪提示
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      # 第七步：列出工作目录文件
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      # 第八步：输出作业最终状态
      - run: echo "🍏 This job's status is ${{ job.status }}."

      
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1 # 保留最近1天的工作流运行记录。
          keep_minimum_runs: 3 # 至少保留3个工作流运行记录，即使它们超过了retain_days指定的天数。
          token: ${{ secrets.GH_TOKEN }}